/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.CompteDAO;
import DAO.EtablissementDAO;
import Entities.Responsable;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yashiro
 */
public class CompteResponsable extends javax.swing.JPanel {

    /**
     * Creates new form statistiques
     */
    public CompteResponsable() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableResponsables = new javax.swing.JTable();
        btnDesactiver = new javax.swing.JButton();
        btnSupprimer = new javax.swing.JButton();
        btnModifier = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });

        jLabel1.setText("Responsables");

        tableResponsables.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableResponsables);

        btnDesactiver.setText("Désactiver");
        btnDesactiver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesactiverActionPerformed(evt);
            }
        });

        btnSupprimer.setText("Supprimer");

        btnModifier.setText("Modifier");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 763, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnModifier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSupprimer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDesactiver)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDesactiver)
                    .addComponent(btnSupprimer)
                    .addComponent(btnModifier))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
           
    }//GEN-LAST:event_formComponentShown
public void afficher(){
        EtablissementDAO ed = new EtablissementDAO();
        CompteDAO resp = new CompteDAO();
        List<Responsable> listresp = new ArrayList<Responsable>();
        listresp= resp.selectAllResponsables();
        String[] colName = new String[] {
           "Pseudo", "Nom", "Prenom", "CIN", "Etablissement", "Emai", "Téléphone", "Etat"
            };
        
        DefaultTableModel model = new DefaultTableModel(colName, WIDTH); 
        tableResponsables.setModel(model);
        //Object[][] data = null;
        //String[] columnNames = new String[3];
        //columnNames = new String[] {"Pseudo","Etablissement",};
        //data = new Object[1][2];
        int i=0;
        int j=0;
        String status="Inconnu";
        for(Responsable r:listresp)
        {
                if(r.getStatus()==1)
                    status="Actif";
                else if(r.getStatus()==0)
                    status="Non Actif";
                
                model.addRow(new Object[]{""});
                tableResponsables.getModel().setValueAt(r.getLogin(),i,j);
                tableResponsables.getModel().setValueAt(r.getNom(),i,j+1);
                tableResponsables.getModel().setValueAt(r.getPrenom(),i,j+2);
                tableResponsables.getModel().setValueAt(r.getCin(),i,j+3);
                tableResponsables.getModel().setValueAt(ed.getEtab(r).getName(),i,j+4);
                tableResponsables.getModel().setValueAt(r.getAdress_mail(),i,j+5);
                tableResponsables.getModel().setValueAt(r.getPhone(),i,j+6);
                tableResponsables.getModel().setValueAt(status,i,j+7);
            
           i+=1;
           //j+=1;
            
        }
        //System.out.println(tableResponsables.getRowCount());
        model.removeRow(tableResponsables.getRowCount()-1);
        
        //DefaultTableCellRenderer leftRenderer = new DefaultTableCellRenderer();
        //leftRenderer.setHorizontalAlignment( JLabel.CENTER );
        //tableResponsables.getColumnModel().getColumn(0).setCellRenderer( leftRenderer );
        //leftRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        desactiver();
    
    
            
}
public void desactiver(){
    tableResponsables.addMouseListener(new java.awt.event.MouseAdapter() {
    @Override
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        int row = tableResponsables.rowAtPoint(evt.getPoint());
        int col = tableResponsables.columnAtPoint(evt.getPoint());
        if (row >=0 && col >=0) {
            
            
            if(tableResponsables.getValueAt(tableResponsables.getSelectedRow(), 7) == "Actif")
                btnDesactiver.setText("Désactiver");
            else if(tableResponsables.getValueAt(tableResponsables.getSelectedRow(), 7) == "Non Actif")
                btnDesactiver.setText("Activer");
            
        }
    }
});


}
                
    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentAdded

    private void btnDesactiverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesactiverActionPerformed
        if(tableResponsables.getValueAt(tableResponsables.getSelectedRow(), 7) == "Actif" )
            btnDesactiver.setText("Activer");
    }//GEN-LAST:event_btnDesactiverActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDesactiver;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableResponsables;
    // End of variables declaration//GEN-END:variables
}
