/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.EtablissementDAO;
import DAO.GouvernoratDAO;
import DAO.ReclamationDAO;
import DAO.VilleDAO;
import Entities.Etablissement;
import Entities.Gouvernorat;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import metier.GeneratePDFEtabGouv;
import metier.GestionReclamation;

/**
 *
 * @author Yashiro
 */
public class stats_gouvernorat extends javax.swing.JPanel {

    /**
     * Creates new form stats_gouvernorat
     */
    public stats_gouvernorat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        gouvtab = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnrapport = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(845, 469));

        gouvtab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(gouvtab);

        jLabel1.setText("Statistiques des Réclamations par Gouvernorat et Etablissement");

        btnrapport.setText("Exporter en PDF");
        btnrapport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrapportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 825, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnrapport)
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnrapport)
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnrapportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrapportActionPerformed
        GeneratePDFEtabGouv gpdf = new GeneratePDFEtabGouv();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        if(gpdf.generate())
        {
                        try {
                JOptionPane.showMessageDialog(null, "Rapport généré");
                File f = new File("Rapport Filtré "+dateFormat.format(new Date())+".pdf");
                Desktop desktop = Desktop.getDesktop();
                desktop.open(f);
            } catch (IOException ex) {
                Logger.getLogger(Statistiques.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Une erreur s'est produite!");
    }//GEN-LAST:event_btnrapportActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnrapport;
    private javax.swing.JTable gouvtab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

public void afficher(){
    
        GouvernoratDAO gd = new GouvernoratDAO();
        EtablissementDAO ed = new EtablissementDAO();
        ReclamationDAO rd = new ReclamationDAO();
        List<Gouvernorat> liste = new ArrayList<Gouvernorat>();
        liste=gd.getAllGouv();
        List<Etablissement> listeEtab = new ArrayList<Etablissement>();
        listeEtab = ed.getAllEtab();
        
        String[] colName = new String[] {
           "Gouvernorat","Etablissement", "Réclamations", "Réclamations résolues", "Réclamations non résolues"
            };
        
        DefaultTableModel model = new DefaultTableModel(colName, WIDTH); 
        
        gouvtab.setModel(model);
        int k=0;
        GestionReclamation grec = new GestionReclamation();
        VilleDAO vd = new VilleDAO();
        
        
        for(Gouvernorat g:liste){
                //int i=1;
                gouvtab.getModel().setValueAt(g.getNomgouv(),k,0);
                
                for(Etablissement e:listeEtab){
                
                
                
                if(vd.checkVilleGouv(g,ed.getVilleForEtab(e))){
                    k+=1;
                    model.addRow(new Object[]{""});
                    gouvtab.getModel().setValueAt("",k,0);
                    gouvtab.getModel().setValueAt(e.getName(),k,1);

                    gouvtab.getModel().setValueAt(rd.totalRec(e),k,2);
                    gouvtab.getModel().setValueAt(grec.getRecResolues(rd.getRecsForEtablissement(e)),k,3);
                    gouvtab.getModel().setValueAt(grec.getRecNonResolues(rd.getRecsForEtablissement(e)),k,4);
                
                }
            }
            model.addRow(new Object[]{""});
            k+=1;
            }
            
        
    
        model.removeRow(gouvtab.getRowCount()-1);
    
    }
    
    
    









}
