/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.EtablissementDAO;
import DAO.ReclamationDAO;
import Entities.Etablissement;
import Entities.Reclamation;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.stage.FileChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import metier.GeneratePDFEtabs;

/**
 *
 * @author Yashiro
 */
public class Statistiques extends javax.swing.JPanel {

    /**
     * Creates new form Statistiques
     */
    public Statistiques() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        stats = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnpdf = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        stats.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(stats);

        jLabel1.setText("Statistiques des Réclamations filtrées par Etablissement");

        btnpdf.setText("Exporter en PDF");
        btnpdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpdfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 825, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnpdf)
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnpdf)
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        
        
    }//GEN-LAST:event_formComponentShown

    private void btnpdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpdfActionPerformed
        
        GeneratePDFEtabs gpdf = new GeneratePDFEtabs();
        
        if(gpdf.generate()){
            try {
                JOptionPane.showMessageDialog(null, "Rapport généré");
                File f = new File("Rapport.pdf");
                Desktop desktop = Desktop.getDesktop();
                desktop.open(f);
            } catch (IOException ex) {
                Logger.getLogger(Statistiques.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Une erreur s'est produite!");
 
    }//GEN-LAST:event_btnpdfActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnpdf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable stats;
    // End of variables declaration//GEN-END:variables

public void afficherStatistiques(){
        ReclamationDAO td = new ReclamationDAO();
        EtablissementDAO ed = new EtablissementDAO();
        
        String[] colName = new String[] {
           "Etablissement", "Réclamations", "Réclamations résolues", "Réclamations non résolues"
            };
        DefaultTableModel model = new DefaultTableModel(colName, WIDTH); 
        stats.setModel(model);
        
        List<Etablissement> le = new ArrayList<Etablissement>();
        le=ed.getAllEtab();
        int k=0;
        for(Etablissement e:le){
            
            stats.getModel().setValueAt(e.getName(),k,0);
            stats.getModel().setValueAt(td.totalRec(e),k,1);
            stats.getModel().setValueAt(td.recTraitees(e),k,2);
            stats.getModel().setValueAt(td.recNonTraitees(e),k,3);
            model.addRow(new Object[]{""});
            k+=1;
        }
        
        model.removeRow(stats.getRowCount()-1);
    
    
}













}