/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.GouvernoratDAO;
import Entities.Gouvernorat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yashiro
 */
public class stats_gouvernorat extends javax.swing.JPanel {

    /**
     * Creates new form stats_gouvernorat
     */
    public stats_gouvernorat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        gouvtab = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(845, 469));

        gouvtab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(gouvtab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 825, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable gouvtab;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

public void afficher(){
    
        GouvernoratDAO gd = new GouvernoratDAO();
        List<Gouvernorat> liste = new ArrayList<Gouvernorat>();
        liste=gd.getAllGouv();
        
        String[] colName = new String[] {
           "Gouvernorat", "Réclamations", "Réclamations résolues", "Réclamations non résolues"
            };
        DefaultTableModel model = new DefaultTableModel(colName, WIDTH); 
        gouvtab.setModel(model);
        int k=0;
        int grecs=0;
                
                
        
        for(Gouvernorat g:liste){
                
            gouvtab.getModel().setValueAt(g.getNomgouv(),k,0);
            gouvtab.getModel().setValueAt(gd.getAllGouvRec(g),k,1);
            model.addRow(new Object[]{""});
            k+=1;
        }
    
        model.removeRow(gouvtab.getRowCount()-1);
    
    
    
    
    
}








}
